name: app_environment
channels:
  - snowflake
dependencies:
  - fastapi=0.112.2
  - geopy=2.4.1
  - pandas=2.2.3
  - pydantic=2.11.7
  - pydeck=0.9.1
  - python=3.11.*
  - requests=2.32.4
  - snowflake-snowpark-python=
  - streamlit=
